baseurl: /jekyll_demo
highlighter: pygments
markdown: redcarpet
# Make redcarpet behave like GitHub Flavored Markdown
# refer to http://sholsinger.com/2014/03/jekyll-github-flavored-markdown
# refer to http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript"]
  
#markdown: kramdown
#kramdown:
#  input: GFM
